//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
    "1.01", ClrNamespace = "www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01")]

namespace www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetSlotMachineJackpotRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetSlotMachineJackpotRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string SlotMachineField;

        private int NumberOfLinesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string SlotMachine
        {
            get
            {
                return this.SlotMachineField;
            }
            set
            {
                this.SlotMachineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public int NumberOfLines
        {
            get
            {
                return this.NumberOfLinesField;
            }
            set
            {
                this.NumberOfLinesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetSlotMachineJackpotResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetSlotMachineJackpotResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.JackpotList JackpotsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.JackpotList Jackpots
        {
            get
            {
                return this.JackpotsField;
            }
            set
            {
                this.JackpotsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "JackpotList", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01", ItemName = "item")]
    public class JackpotList : System.Collections.Generic.List<www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.JackpotDetail>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ErrorList", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01", ItemName = "item")]
    public class ErrorList : System.Collections.Generic.List<www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ProcessError>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "JackpotDetail", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class JackpotDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private double AmountField;

        private System.DateTime HitDateField;

        private string JPotTypeField;

        private string SlotMachineField;

        private string DescriptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime HitDate
        {
            get
            {
                return this.HitDateField;
            }
            set
            {
                this.HitDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string JPotType
        {
            get
            {
                return this.JPotTypeField;
            }
            set
            {
                this.JPotTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string SlotMachine
        {
            get
            {
                return this.SlotMachineField;
            }
            set
            {
                this.SlotMachineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ProcessError", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class ProcessError : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ErrorMessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetJackpotPayoutRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetJackpotPayoutRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime StartField;

        private System.DateTime EndField;

        private int NumberOfLinesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int NumberOfLines
        {
            get
            {
                return this.NumberOfLinesField;
            }
            set
            {
                this.NumberOfLinesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetJackpotPayoutResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetJackpotPayoutResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private long JackpotTotalField;

        private long ProgressiveTotalField;

        private long CelebrationTotalField;

        private long MysteryTotalField;

        private long MachineOutMovementField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.JackpotList JackpotsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public long JackpotTotal
        {
            get
            {
                return this.JackpotTotalField;
            }
            set
            {
                this.JackpotTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public long ProgressiveTotal
        {
            get
            {
                return this.ProgressiveTotalField;
            }
            set
            {
                this.ProgressiveTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public long CelebrationTotal
        {
            get
            {
                return this.CelebrationTotalField;
            }
            set
            {
                this.CelebrationTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public long MysteryTotal
        {
            get
            {
                return this.MysteryTotalField;
            }
            set
            {
                this.MysteryTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public long MachineOutMovement
        {
            get
            {
                return this.MachineOutMovementField;
            }
            set
            {
                this.MachineOutMovementField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.JackpotList Jackpots
        {
            get
            {
                return this.JackpotsField;
            }
            set
            {
                this.JackpotsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayersRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CheckPlayerRequest))]
    public partial class GetPlayersRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool DetailField;

        private System.DateTime StartField;

        private System.DateTime EndField;

        private long MinVisitsField;

        private long MaxVisitsField;

        private long MinPointsField;

        private long MaxPointsField;

        private long MinSlotsPointsField;

        private long MaxSlotsPointsField;

        private long MinTablesPointsField;

        private long MaxTablesPointsField;

        private long MinTIField;

        private long MaxTIField;

        private long MinTDField;

        private long MaxTDField;

        private long MinTHField;

        private long MaxTHField;

        private long MinAvgDailyField;

        private long MaxAvgDailyField;

        private long MinAgeField;

        private long MaxAgeField;

        private long BirthdayMonthField;

        private string BirthdayDateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                this.DetailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public long MinVisits
        {
            get
            {
                return this.MinVisitsField;
            }
            set
            {
                this.MinVisitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public long MaxVisits
        {
            get
            {
                return this.MaxVisitsField;
            }
            set
            {
                this.MaxVisitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public long MinPoints
        {
            get
            {
                return this.MinPointsField;
            }
            set
            {
                this.MinPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public long MaxPoints
        {
            get
            {
                return this.MaxPointsField;
            }
            set
            {
                this.MaxPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public long MinSlotsPoints
        {
            get
            {
                return this.MinSlotsPointsField;
            }
            set
            {
                this.MinSlotsPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public long MaxSlotsPoints
        {
            get
            {
                return this.MaxSlotsPointsField;
            }
            set
            {
                this.MaxSlotsPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public long MinTablesPoints
        {
            get
            {
                return this.MinTablesPointsField;
            }
            set
            {
                this.MinTablesPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public long MaxTablesPoints
        {
            get
            {
                return this.MaxTablesPointsField;
            }
            set
            {
                this.MaxTablesPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public long MinTI
        {
            get
            {
                return this.MinTIField;
            }
            set
            {
                this.MinTIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public long MaxTI
        {
            get
            {
                return this.MaxTIField;
            }
            set
            {
                this.MaxTIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public long MinTD
        {
            get
            {
                return this.MinTDField;
            }
            set
            {
                this.MinTDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public long MaxTD
        {
            get
            {
                return this.MaxTDField;
            }
            set
            {
                this.MaxTDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 15)]
        public long MinTH
        {
            get
            {
                return this.MinTHField;
            }
            set
            {
                this.MinTHField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 16)]
        public long MaxTH
        {
            get
            {
                return this.MaxTHField;
            }
            set
            {
                this.MaxTHField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 17)]
        public long MinAvgDaily
        {
            get
            {
                return this.MinAvgDailyField;
            }
            set
            {
                this.MinAvgDailyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 18)]
        public long MaxAvgDaily
        {
            get
            {
                return this.MaxAvgDailyField;
            }
            set
            {
                this.MaxAvgDailyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 19)]
        public long MinAge
        {
            get
            {
                return this.MinAgeField;
            }
            set
            {
                this.MinAgeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 20)]
        public long MaxAge
        {
            get
            {
                return this.MaxAgeField;
            }
            set
            {
                this.MaxAgeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 21)]
        public long BirthdayMonth
        {
            get
            {
                return this.BirthdayMonthField;
            }
            set
            {
                this.BirthdayMonthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 22)]
        public string BirthdayDate
        {
            get
            {
                return this.BirthdayDateField;
            }
            set
            {
                this.BirthdayDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CheckPlayerRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class CheckPlayerRequest : www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersRequest
    {

        private string AcctNoField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayersResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPlayersResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private int PlayerNumField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PlayerList PlayersField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public int PlayerNum
        {
            get
            {
                return this.PlayerNumField;
            }
            set
            {
                this.PlayerNumField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PlayerList Players
        {
            get
            {
                return this.PlayersField;
            }
            set
            {
                this.PlayersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "PlayerList", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01", ItemName = "item")]
    public class PlayerList : System.Collections.Generic.List<www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PlayerDetail>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlayerDetail", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class PlayerDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        private string TitleField;

        private string InitialsField;

        private string FirstNameField;

        private string LastNameField;

        private string IdField;

        private string PassportField;

        private string CardTierField;

        private bool CanCommunicateSMSField;

        private bool CanCommunicateEmailField;

        private string ContactTelField;

        private string EmailAddressField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string Initials
        {
            get
            {
                return this.InitialsField;
            }
            set
            {
                this.InitialsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public string Passport
        {
            get
            {
                return this.PassportField;
            }
            set
            {
                this.PassportField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public string CardTier
        {
            get
            {
                return this.CardTierField;
            }
            set
            {
                this.CardTierField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public bool CanCommunicateSMS
        {
            get
            {
                return this.CanCommunicateSMSField;
            }
            set
            {
                this.CanCommunicateSMSField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public bool CanCommunicateEmail
        {
            get
            {
                return this.CanCommunicateEmailField;
            }
            set
            {
                this.CanCommunicateEmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public string ContactTel
        {
            get
            {
                return this.ContactTelField;
            }
            set
            {
                this.ContactTelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayerPermissionRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPlayerPermissionRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayersPermissionResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPlayersPermissionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PlayerDetail PlayerField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PlayerDetail Player
        {
            get
            {
                return this.PlayerField;
            }
            set
            {
                this.PlayerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetAccountRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CardNoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CardNo
        {
            get
            {
                return this.CardNoField;
            }
            set
            {
                this.CardNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetAccountResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private string AcctNoField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayerPlayRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPlayerPlayRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        private System.DateTime StartField;

        private System.DateTime EndField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPlayerPlayResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPlayerPlayResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private long SlotsPointsField;

        private long TablesPointsField;

        private long AdjustedPointsField;

        private long BonusPointsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public long SlotsPoints
        {
            get
            {
                return this.SlotsPointsField;
            }
            set
            {
                this.SlotsPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public long TablesPoints
        {
            get
            {
                return this.TablesPointsField;
            }
            set
            {
                this.TablesPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public long AdjustedPoints
        {
            get
            {
                return this.AdjustedPointsField;
            }
            set
            {
                this.AdjustedPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public long BonusPoints
        {
            get
            {
                return this.BonusPointsField;
            }
            set
            {
                this.BonusPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetActiveCardsRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetActiveCardsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetActiveCardsResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetActiveCardsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CardList CardsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CardList Cards
        {
            get
            {
                return this.CardsField;
            }
            set
            {
                this.CardsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "CardList", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01", ItemName = "item")]
    public class CardList : System.Collections.Generic.List<www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CardNumbers>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CardNumbers", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class CardNumbers : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CardNumberField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPointsBalancesRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPointsBalancesRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPointsBalanceResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPointsBalanceResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private long CasinPointsField;

        private long LeisurePointsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public long CasinPoints
        {
            get
            {
                return this.CasinPointsField;
            }
            set
            {
                this.CasinPointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public long LeisurePoints
        {
            get
            {
                return this.LeisurePointsField;
            }
            set
            {
                this.LeisurePointsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPointsTranRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPointsTranRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcctNoField;

        private System.DateTime QueryDateField;

        private string CasinoCodeField;

        private System.DateTime ZeroDateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string AcctNo
        {
            get
            {
                return this.AcctNoField;
            }
            set
            {
                this.AcctNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime QueryDate
        {
            get
            {
                return this.QueryDateField;
            }
            set
            {
                this.QueryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string CasinoCode
        {
            get
            {
                return this.CasinoCodeField;
            }
            set
            {
                this.CasinoCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.DateTime ZeroDate
        {
            get
            {
                return this.ZeroDateField;
            }
            set
            {
                this.ZeroDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPointsTranResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetPointsTranResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PointsTran PointsTransactionField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.PointsTran PointsTransaction
        {
            get
            {
                return this.PointsTransactionField;
            }
            set
            {
                this.PointsTransactionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PointsTran", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class PointsTran : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime DateField;

        private string PropertyField;

        private long EarnedCasinoField;

        private long BonusCasinoField;

        private long AdjPosCasinoField;

        private long RedeemCasinoField;

        private long AdjNegCasinoField;

        private long ExpireCasinoField;

        private long EarnedLeisureField;

        private long AdjPosLeisureField;

        private long RedeemLeisureField;

        private long AdjNegLeisureField;

        private long ExpireLeisureField;

        private long TierCreditsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Property
        {
            get
            {
                return this.PropertyField;
            }
            set
            {
                this.PropertyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public long EarnedCasino
        {
            get
            {
                return this.EarnedCasinoField;
            }
            set
            {
                this.EarnedCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public long BonusCasino
        {
            get
            {
                return this.BonusCasinoField;
            }
            set
            {
                this.BonusCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public long AdjPosCasino
        {
            get
            {
                return this.AdjPosCasinoField;
            }
            set
            {
                this.AdjPosCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public long RedeemCasino
        {
            get
            {
                return this.RedeemCasinoField;
            }
            set
            {
                this.RedeemCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public long AdjNegCasino
        {
            get
            {
                return this.AdjNegCasinoField;
            }
            set
            {
                this.AdjNegCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public long ExpireCasino
        {
            get
            {
                return this.ExpireCasinoField;
            }
            set
            {
                this.ExpireCasinoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public long EarnedLeisure
        {
            get
            {
                return this.EarnedLeisureField;
            }
            set
            {
                this.EarnedLeisureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 9)]
        public long AdjPosLeisure
        {
            get
            {
                return this.AdjPosLeisureField;
            }
            set
            {
                this.AdjPosLeisureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public long RedeemLeisure
        {
            get
            {
                return this.RedeemLeisureField;
            }
            set
            {
                this.RedeemLeisureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public long AdjNegLeisure
        {
            get
            {
                return this.AdjNegLeisureField;
            }
            set
            {
                this.AdjNegLeisureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 12)]
        public long ExpireLeisure
        {
            get
            {
                return this.ExpireLeisureField;
            }
            set
            {
                this.ExpireLeisureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 13)]
        public long TierCredits
        {
            get
            {
                return this.TierCreditsField;
            }
            set
            {
                this.TierCreditsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetGameCelebrationsValueRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetGameCelebrationsValueRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private long AmountField;

        private long NumberOfLinesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long NumberOfLines
        {
            get
            {
                return this.NumberOfLinesField;
            }
            set
            {
                this.NumberOfLinesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetGameCelebrationsResponse", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetGameCelebrationsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool SuccessField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GameCelebrationsList PayoutsField;

        private www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList ErrorsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GameCelebrationsList Payouts
        {
            get
            {
                return this.PayoutsField;
            }
            set
            {
                this.PayoutsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.ErrorList Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "GameCelebrationsList", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01", ItemName = "item")]
    public class GameCelebrationsList : System.Collections.Generic.List<www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GameCelebrationsDetail>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GameCelebrationsDetail", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GameCelebrationsDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private long AmountField;

        private string SlotMachineField;

        private System.DateTime HitDateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string SlotMachine
        {
            get
            {
                return this.SlotMachineField;
            }
            set
            {
                this.SlotMachineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.DateTime HitDate
        {
            get
            {
                return this.HitDateField;
            }
            set
            {
                this.HitDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetGameCelebrationsMachineRequest", Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01")]
    public partial class GetGameCelebrationsMachineRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MachineNoField;

        private long AmountField;

        private long NumberOfLinesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string MachineNo
        {
            get
            {
                return this.MachineNoField;
            }
            set
            {
                this.MachineNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public long NumberOfLines
        {
            get
            {
                return this.NumberOfLinesField;
            }
            set
            {
                this.NumberOfLinesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
    "1.01", ConfigurationName = "SlotsInfoService")]
public interface SlotsInfoService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetMachineJackpots", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetMachineJackpotsResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetSlotMachineJackpotResponse GetMachineJackpots(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetSlotMachineJackpotRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetJackpotPayouts", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetJackpotPayoutsResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetJackpotPayoutResponse GetJackpotPayouts(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetJackpotPayoutRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerSearch", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerSearchResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersResponse GetPlayerSearch(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/CheckPlayerSearch", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/CheckPlayerSearchResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersResponse CheckPlayerSearch(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CheckPlayerRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerPermissions", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerPermissionsResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersPermissionResponse GetPlayerPermissions(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPermissionRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerAccount", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerAccountResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetAccountResponse GetPlayerAccount(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetAccountRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerPlayInfo", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerPlayInfoResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPlayResponse GetPlayerPlayInfo(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPlayRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerActiveCards", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPlayerActiveCardsResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetActiveCardsResponse GetPlayerActiveCards(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetActiveCardsRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPointsBalances", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPointsBalancesResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsBalanceResponse GetPointsBalances(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsBalancesRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPointsTransaction", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetPointsTransactionResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsTranResponse GetPointsTransaction(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsTranRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetGameCelebrationsByValue", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetGameCelebrationsByValueResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsResponse GetGameCelebrationsByValue(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsValueRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetGameCelebrationsByMachine", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/GetGameCelebrationsByMachineResponse")]
    www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsResponse GetGameCelebrationsByMachine(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsMachineRequest reqst);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/TestConnection", ReplyAction = "http://www.suninternational.com/schemas/SunIntSchemas/gaming/property/SlotsInfo/v" +
        "1.01/SlotsInfoService/TestConnectionResponse")]
    void TestConnection();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SlotsInfoServiceChannel : SlotsInfoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SlotsInfoServiceClient : System.ServiceModel.ClientBase<SlotsInfoService>, SlotsInfoService
{

    public SlotsInfoServiceClient()
    {
    }

    public SlotsInfoServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public SlotsInfoServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SlotsInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SlotsInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetSlotMachineJackpotResponse GetMachineJackpots(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetSlotMachineJackpotRequest reqst)
    {
        return base.Channel.GetMachineJackpots(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetJackpotPayoutResponse GetJackpotPayouts(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetJackpotPayoutRequest reqst)
    {
        return base.Channel.GetJackpotPayouts(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersResponse GetPlayerSearch(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersRequest reqst)
    {
        return base.Channel.GetPlayerSearch(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersResponse CheckPlayerSearch(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.CheckPlayerRequest reqst)
    {
        return base.Channel.CheckPlayerSearch(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayersPermissionResponse GetPlayerPermissions(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPermissionRequest reqst)
    {
        return base.Channel.GetPlayerPermissions(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetAccountResponse GetPlayerAccount(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetAccountRequest reqst)
    {
        return base.Channel.GetPlayerAccount(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPlayResponse GetPlayerPlayInfo(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPlayerPlayRequest reqst)
    {
        return base.Channel.GetPlayerPlayInfo(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetActiveCardsResponse GetPlayerActiveCards(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetActiveCardsRequest reqst)
    {
        return base.Channel.GetPlayerActiveCards(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsBalanceResponse GetPointsBalances(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsBalancesRequest reqst)
    {
        return base.Channel.GetPointsBalances(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsTranResponse GetPointsTransaction(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetPointsTranRequest reqst)
    {
        return base.Channel.GetPointsTransaction(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsResponse GetGameCelebrationsByValue(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsValueRequest reqst)
    {
        return base.Channel.GetGameCelebrationsByValue(reqst);
    }

    public www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsResponse GetGameCelebrationsByMachine(www.suninternational.com.schemas.SunIntSchemas.gaming.property.SlotsInfo.v1._01.GetGameCelebrationsMachineRequest reqst)
    {
        return base.Channel.GetGameCelebrationsByMachine(reqst);
    }

    public void TestConnection()
    {
        base.Channel.TestConnection();
    }
}
